### ISSUE TITLE
Generate minimum and maximum value of range

### ISSUE THREAD

**Issue by wundrian** [forcedotcom/comdagen#3]
This is a historic proposal from @ojauch:
When generating product sets the user defines a range how many products should be part of each product set. For example:
```
productSets:
    # number of product sets to generate
    elementCount: 10

    # define range of products per product set
    minSetProducts: 3
    maxSetProducts: 8
```

In this configuration the user configured that 10 product sets should get generated with 3 to 8 products each. In the current implementation it is not guaranteed that comdagen generates at least one product set with the minimum number of products and one with the maximum number of products.

Should this get changed that the result of the product set generation is more predictable? The same applies to product bundles, variation products, etc.
